[[article]]

id = "001"
title = "The founding of Weight in the Attention, a journal for the AIGC Zeitgeist"
authors = ["Neruthes (WITA Editor)"]
authors_simple = "Neruthes (WITA Editor)"
date = "2025-07-13"
