[[article]]

id = "001"
title = "The founding of Weight in the Attention, a journal for the AIGC Zeitgeist"
authors = ["Neruthes (WITA Editor)"]
authors_simple = "Neruthes"
date = "2025-07-17"
license = "CC BY-ND 4.0"
