[[article]]

id = "002"
title = "WITA Manuscript Submission Guide"
authors = ["Neruthes (WITA Editor)"]
authors_simple = "Neruthes"
date = "2025-07-14"
license = "CC BY-ND 4.0"
abstract = """
Like most journals, Weight in the Attention (WITA) handles manuscript submissions.
A rare characteristic of WITA is that the submission process is based on Git, GitHub, and pull request.
This guide offers a comprehensive guide for authors in good faith of establishing an efficient manuscript acceptance workflow.
Key takeaway—if you would like to submit an already published article, just open an issue and include URL to your article.
"""
