[[article]]

id = "003"
title = "My Startup Is Just a Claude Wrapper, but It’s a Free Claude Wrapper"
authors = ["Neruthes", "ChatGPT (OpenAI)"]
authors_simple = "Neruthes, et al."
date = "2025-07-14"
license = "Public Domain"
