[[article]]

id = "004"
title = "Navigating the AI Geoscape: A Multi-Faceted Analysis of Manus AI's Strategic Retreat from Mainland China"
authors = ["Neruthes", "Gemini (Google)"]
authors_simple = "Neruthes, et al."
date = "2025-07-14"
license = "Public Domain"
